import type { Metadata } from "next"
import "../globals.css"
import Header from "@/components/main_site/header/header"
import { poppins } from "@/components/ui/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Header />
        {/*<main className="mt-[52px] md:mt-[96px]">{children}</main>*/}
        <main className="">{children}</main>
      </body>
    </html>
  )
}
